export const CATEGORIES = [
  { id: 'organicos', title: 'Orgánicos', subtitle: 'Restos de comida y de jardín', color: '#376b3d', tint: 'rgba(55,107,61,.6)', width: 90, height: 69, crop: { width: '365.82%', height: '354.1%', left: '-40.51%', top: '-39.34%' }, description: 'Son restos de origen vegetal que pueden descomponerse y aprovecharse para producir compost', includes: ['Yerba, café y té', 'Cáscaras de frutas y verduras', 'Hojas secas y ramitas', 'Cáscaras de huevo'], actions: ['Separarlos del resto de la basura', 'Aprovecharlos para reducir la cantidad de residuos que descartás', '¡Podés armar tu propio compost en casa!'], advice: 'Podés transformar tus residuos orgánicos en abono natural. Aprendé más con Ciervito', link: '/compostar' },
  { id: 'papel', title: 'Papel y Cartón', subtitle: 'Cajas y papeles limpios', color: '#805719', tint: 'rgba(128,87,25,.6)', width: 90, height: 65.676, crop: { width: '312.43%', height: '320%', left: '-185.41%', top: '-181.48%' }, description: 'Son materiales que pueden recuperarse para fabricar nuevos productos.', includes: ['Cajas de cartón', 'Hojas de cuadernos', 'Diarios y revistas', 'Carpetas y papeles limpios'], actions: ['Reutilizar las hojas y cajas antes de descartarlas', 'Doblar las cajas para ocupar menos espacio', 'Mantener el papel seco y sin restos de comida', 'Llevarlos a un punto verde habilitado'], advice: 'Reutilizá todo lo que puedas antes de reciclar' },
  { id: 'plasticos', title: 'Plásticos', subtitle: 'Botellas y envases', color: '#236779', tint: 'rgba(35,103,121,.6)', width: 70, height: 69, crop: { width: '409.93%', height: '310.79%', left: '-258.16%', top: '-25.18%' }, description: 'Botellas, envases y otros objetos de plástico que pueden recuperarse si se separan correctamente.', includes: ['Botellas y bidones', 'Envases de productos', 'Bolsas y envoltorios', 'Vasos y recipientes'], actions: ['Separarlos de los demás residuos', 'Vaciar los envases y limpiarlos', 'Llevarlos a un Punto Verde que los reciba'], advice: 'Elegí alternativas reutilizables en lugar de bolsas, vasos y cubiertos descartables cuando sea posible' },
  { id: 'vidrios', title: 'Vidrios', subtitle: 'Botellas y frascos', color: '#704486', tint: 'rgba(112,68,134,.6)', width: 60, height: 72, crop: { width: '507.02%', height: '314.29%', left: '-79.82%', top: '-170.24%' }, description: 'Son botellas, frascos y otros envases de vidrio que pueden reutilizarse o recuperarse si se separan correctamente.', includes: ['Botellas de vidrio', 'Frascos de vidrio', 'Objetos de vidrio'], actions: ['Reutilizar frascos y botellas cuando sea posible', 'Vaciar los recipientes antes de separarlos', 'Llevarlos a un Punto Verde que los reciba'], advice: 'No mezcles vidrio roto con envases intactos, consultá cómo disponerlos de manera segura.' },
]

// Las preguntas 1 y 4 provienen de Figma; las restantes siguen el contenido de las fichas.
export const QUESTIONS = [
  { question: '¿Qué deberías hacer con una botella de plástico vacía antes de llevarla a un Punto Verde que la recibe?', options: ['Mezclarla con restos de comida', 'Dejarla con líquido y restos de bebida', 'Vaciarla y limpiarla si hace falta', 'Quemarla para reducir su tamaño'], correct: 2, explanation: 'Vaciá y limpiá los envases antes de separarlos.' },
  { question: '¿Cuál de estos residuos es orgánico?', options: ['Una botella de vidrio', 'Cáscaras de frutas y verduras', 'Un envase de plástico', 'Una caja de cartón'], correct: 1, explanation: 'Las cáscaras de frutas y verduras pueden aprovecharse para producir compost.' },
  { question: '¿Qué podés hacer con un frasco de vidrio vacío?', options: ['Mezclarlo con restos de comida', 'Quemarlo', 'Romperlo para ocupar menos espacio', 'Reutilizarlo o llevarlo a un Punto Verde que lo reciba'], correct: 3, explanation: 'Reutilizá los frascos cuando sea posible y consultá qué recibe tu Punto Verde.' },
  { question: '¿Qué deberías hacer con una caja de cartón limpia antes de separarla?', options: ['Mezclarla con residuos orgánicos', 'Mojarla para ablandarla', 'Plegarla y mantenerla seca y limpia', 'Ensuciarla con restos de comida'], correct: 2, explanation: 'Plegar las cajas ahorra espacio. El cartón debe mantenerse seco y limpio.' },
  { question: '¿Cuál es una forma de reducir los residuos plásticos?', options: ['Elegir bolsas, vasos y cubiertos reutilizables', 'Usar más productos descartables', 'Mezclar todos los residuos', 'Quemar los envases vacíos'], correct: 0, explanation: 'Elegir alternativas reutilizables reduce los productos descartables.' },
]
